name: Naukri Job Agent

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Chromium for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Run script
        run: node jobAgent.js
